# Generated by Django 4.1.3 on 2022-12-09 17:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0006_alter_judge_user'),
        ('coffee', '0005_coffeeaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rating_entity', to='coffee.legalentity', verbose_name='Entidad')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rating_judge_entity', to='judge.judge', verbose_name='Juez')),
            ],
            options={
                'verbose_name': 'Calificación de entidad',
                'verbose_name_plural': 'Calificación de entidades',
            },
        ),
        migrations.CreateModel(
            name='CoffeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rating_coffee', to='coffee.coffeeaddress', verbose_name='Cafetería')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rating_judge_coffee', to='judge.judge', verbose_name='Juez')),
            ],
            options={
                'verbose_name': 'Calificación de cafetería',
                'verbose_name_plural': 'Calificación de cafeterías',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rating_brand', to='coffee.brand', verbose_name='Marca')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rating_judge_brand', to='judge.judge', verbose_name='Juez')),
            ],
            options={
                'verbose_name': 'Calificación de marca',
                'verbose_name_plural': 'Calificación de marcas',
            },
        ),
        migrations.AddConstraint(
            model_name='legalentity',
            constraint=models.UniqueConstraint(fields=('entity', 'judge'), name='unique_rating_entity_judge'),
        ),
        migrations.AddConstraint(
            model_name='coffeeaddress',
            constraint=models.UniqueConstraint(fields=('coffee', 'judge'), name='unique_rating_coffee_judge'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('brand', 'judge'), name='unique_rating_brand_judge'),
        ),
    ]
