# Generated by Django 4.1.3 on 2022-12-09 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0002_remove_judge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
