# Generated by Django 4.1.3 on 2022-12-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_judge_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
