# Generated by Django 4.1.3 on 2022-12-09 16:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0004_delete_judge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Reputación')),
                ('can_comment', models.BooleanField(default=False, verbose_name='Puede comentar?')),
                ('can_rank', models.BooleanField(default=False, verbose_name='Puede calificar?')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
