# Generated by Django 4.1.3 on 2022-12-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_alter_judge_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judge',
            options={'verbose_name': 'Juez', 'verbose_name_plural': 'Jueces'},
        ),
    ]
