# Generated by Django 4.1.3 on 2022-12-20 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0007_alter_judge_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='judge', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
