# Generated by Django 4.1.3 on 2022-12-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalentity',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
    ]
