# Generated by Django 4.1.3 on 2022-12-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_brand_brand_unique_coffee_brand_name_legal_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entity', to='coffee.legalentity', verbose_name='Entidad'),
        ),
    ]
