# Generated by Django 4.1.3 on 2022-12-03 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('coffee', '0004_alter_brand_legal_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='brand', to='coffee.brand', verbose_name='Marca')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='city', to='common.city', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.AddConstraint(
            model_name='coffeeaddress',
            constraint=models.UniqueConstraint(fields=('city', 'address', 'brand'), name='unique_coffee_coffee_address_city_address_brand'),
        ),
    ]
